// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"architecture.md": () => import("../content/docs/architecture.md?collection=docs"), "attestation.md": () => import("../content/docs/attestation.md?collection=docs"), "getting-started.md": () => import("../content/docs/getting-started.md?collection=docs"), "guardrails.md": () => import("../content/docs/guardrails.md?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "vllm.md": () => import("../content/docs/vllm.md?collection=docs"), "api/authentication.md": () => import("../content/docs/api/authentication.md?collection=docs"), "api/chat-completions.md": () => import("../content/docs/api/chat-completions.md?collection=docs"), "api/completions.md": () => import("../content/docs/api/completions.md?collection=docs"), "api/embeddings.md": () => import("../content/docs/api/embeddings.md?collection=docs"), "api/models.md": () => import("../content/docs/api/models.md?collection=docs"), "api/overview.md": () => import("../content/docs/api/overview.md?collection=docs"), "api/routes.md": () => import("../content/docs/api/routes.md?collection=docs"), "api/speech-to-text.md": () => import("../content/docs/api/speech-to-text.md?collection=docs"), "api/translations.md": () => import("../content/docs/api/translations.md?collection=docs"), "auth/pats.md": () => import("../content/docs/auth/pats.md?collection=docs"), "developer-guide/auth-and-request-flow.md": () => import("../content/docs/developer-guide/auth-and-request-flow.md?collection=docs"), "developer-guide/chat-ui.md": () => import("../content/docs/developer-guide/chat-ui.md?collection=docs"), "developer-guide/cvm-management.md": () => import("../content/docs/developer-guide/cvm-management.md?collection=docs"), "developer-guide/fine-tuning.md": () => import("../content/docs/developer-guide/fine-tuning.md?collection=docs"), "developer-guide/hal.md": () => import("../content/docs/developer-guide/hal.md?collection=docs"), "developer-guide/index.md": () => import("../content/docs/developer-guide/index.md?collection=docs"), "developer-guide/private-model-upload.md": () => import("../content/docs/developer-guide/private-model-upload.md?collection=docs"), "integrations/continue.md": () => import("../content/docs/integrations/continue.md?collection=docs"), "integrations/opencode.md": () => import("../content/docs/integrations/opencode.md?collection=docs"), "ui/ui-overview.md": () => import("../content/docs/ui/ui-overview.md?collection=docs"), }),
};
export default browserCollections;